# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsid',
            name='used',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5904\u7406'),
        ),
    ]
